# my global config - Mandeep
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'kubernetes-nodes'

    scheme: https

    bearer_token_file: /resources/user_token
    tls_config:
      ca_file: /resources/ca.crt

    kubernetes_sd_configs:
    - role: node
      api_server: https://192.168.99.114:8443
      bearer_token_file: /resources/user_token
      tls_config:
        ca_file: /resources/ca.crt
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: 192.168.99.114:8443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'k8s-pods'

    scheme: https

    bearer_token_file: /resources/user_token
    tls_config:
      ca_file: /resources/ca.crt

    kubernetes_sd_configs:
    - role: pod
      api_server: https://192.168.99.114:8443
      bearer_token_file: /resources/user_token
      tls_config:
        ca_file: /resources/ca.crt
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - target_label: __address__
        replacement: 192.168.99.114:8443
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        regex: ^$
        replacement: http
        target_label: __meta_kubernetes_pod_annotation_prometheus_io_scheme
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: ^$
        replacement: "8080"
        target_label: __meta_kubernetes_pod_annotation_prometheus_io_port
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        regex: (.+)
        replacement: ${1}
        target_label: __metrics_path__
      - source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        - __meta_kubernetes_pod_name
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __metrics_path__
        regex: (.+);(.+);(.+);(.+);(.+)
        action: replace
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/${1}/pods/${2}:${3}:${4}/proxy${5}
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: kubernetes_node_name
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance

  - job_name: 'k8s-services'

    scheme: https

    bearer_token_file: /resources/user_token
    tls_config:
      ca_file: /resources/ca.crt

    kubernetes_sd_configs:
    - role: service
      api_server: https://192.168.99.114:8443
      bearer_token_file: /resources/user_token
      tls_config:
        ca_file: /resources/ca.crt
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - target_label: __address__
      replacement: 192.168.99.114:8443
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      regex: ^$
      replacement: http
      target_label: __meta_kubernetes_service_annotation_prometheus_io_scheme
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
      regex: ^$
      replacement: "8080"
      target_label: __meta_kubernetes_service_annotation_prometheus_io_port
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      regex: (.+)
      replacement: ${1}
      target_label: __metrics_path__
    - source_labels:
      - __meta_kubernetes_namespace
      - __meta_kubernetes_service_annotation_prometheus_io_scheme
      - __meta_kubernetes_service_name
      - __meta_kubernetes_service_annotation_prometheus_io_port
      - __metrics_path__
      regex: (.+);(.+);(.+);(.+);(.+)
      action: replace
      target_label: __metrics_path__
      replacement: /api/v1/namespaces/${1}/services/${2}:${3}:${4}/proxy${5}
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: kubernetes_service_name
    - source_labels: [__meta_kubernetes_service_name]
      target_label: instance